### ISSUE TITLE
Wireframes for Programs and Events page(s)

### ISSUE THREAD

**Issue by kristinashu** [mozillascience/site#100]
Based on IA https://redpen.io/p/je92d9783cd2855569

We need to determine if Events will fall under Programs or stand on its own.

We can also reference fellowship wireframes https://github.com/mozillascience/site/issues/93

**Comment by hannahkane** [comment]
Will add some notes from our call this morning:
- main goal of page is for visitors to understand the nature of each program—what it is, what involvement looks like
- page should be scalable as new programs may be added (e.g. Workshops, Cohort, Minigrants, etc.)
- the content in the "Our Programs" section of the [copy doc](https://docs.google.com/document/d/1k2Ds-iw4B_Sh5ae1areW1qfuLPtSqmgohtXYBkOi7r4/edit#) might be useful

**Comment by kristinashu** [comment]
Wireframes for all the pages are here https://redpen.io/p/eb9d7534bcf4dfcc17

Some of them are fairly high level but it's good to see all the pages together to make sure we're not missing any major sections. This will also be helpful to reference while writing copy for the rest of the pages.

In this ticket we're focusing on all the Program pages (Events, Study Groups and Fellowships) but please feel free to comment on any the pages.

Note, we initially thought of having a Program landing page but since the home page covers everything that would be there we have removed it.

cc @hannahkane @acabunoc @kaythaney @auremoser @zee-moz @stephwright

**Comment by kristinashu** [comment]
Closing this ticket. Wireframes have been updated based on feedback and cover all the functionality. We can get into more of the details at the design stage.
