### ISSUE TITLE
Homepage comps

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#101]
Let's take the wireframes and final copy we've (nearly!) agreed upon, and create comps. @kristinashu - feel free to fill this in more (or separate out the iconography/photo-finding tasks into separate tickets), but I think this includes:
- [ ] applying Mozmaker styles
- [ ] iconography for the equation at the top
- [ ] finding appropriate images for each section
- [ ] any additional design elements?

**Comment by kristinashu** [comment]
Here's the comp: https://redpen.io/hze34bdcf69992b631

We've kept the site colorful and inviting while still looking professional and slick. To play off the logo, we've worked in overlapping elements like the overlapping content blocks and also the little logo element line pieces.

Some of the interactions I'm thinking are that the top nav bar would stick to the top of the page so the nav is always accessible. We could add some subtle parallax effects. For example, the two large background images could stay fixed while the content scrolls over top of it. Also, the logo element line pieces could scroll at a slightly different speed than the rest of the content to give the site more depth.

To stay on brand with MoFo, we've used our unified color palette, line icon style and Fira font.

**Comment by hannahkane** [comment]
Beautiful work, @kristinashu. I added some comments from a product perspective. Assuming this will get reviewed at design crit on Wednesday - true?

**Comment by kristinashu** [comment]
Thanks @hannahkane. Yes, I will share at crit, although Cassie and Ricardo have already seen.

**Comment by hannahkane** [comment]
flagging for @acabunoc @kaythaney @auremoser @zee-moz @stephwright to take a look and leave comments, too

**Comment by kristinashu** [comment]
I've updated the comp with feedback from both the design team and science team: https://redpen.io/hze34bdcf69992b631

**Comment by kristinashu** [comment]
Closing but please feel free to add comments in redpen.
