### ISSUE TITLE
Determine which pages will be on our CMS

### ISSUE THREAD

**Issue by kristinashu** [mozillascience/site#102]
Here are some high level wireframes for each page to help determine which ones are CMS candidates:
https://invis.io/7T6HVRIB5
Click on the purple IA boxes to see the wireframe for that page. Click anywhere on the wireframe to go back to the IA.

cc @hannahkane

**Comment by hannahkane** [comment]
Thanks, @kristinashu. I went through and took a first pass at which pages would be CMS-appropriate. Will need feedback from others (flagged in the related [/plan ticket](https://github.com/MozillaFoundation/plan/issues/763)).

**Comment by acabunoc** [comment]
I talked to @alicoding about some technical implementation details on CMS that helped me think about how we can use the CMS for science. I left a few comments.

Two areas I don't *think* we'll be able to store data in the CMS. OR we'll need a way to write to the CMS database from the node side of the app.

1. Users
  * With the github login, user profiles are based on their github login
2. Projects
  * Again built around github

**Comment by kristinashu** [comment]
Commenting in Invision is driving me crazy so I've upload the wireframes to redpen instead https://redpen.io/p/eb9d7534bcf4dfcc17

**Comment by hannahkane** [comment]
I think we can close this, based on our meeting on Tuesday. Notes for posterity: https://public.etherpad-mozilla.org/p/sciencesiteapproach
