### ISSUE TITLE
Link to old blog posts?

### ISSUE THREAD

**Issue by BillMills** [mozillascience/site#15]
Sorry if I'm just being unobservant, but I can't seem to find a pagination or 'older' link to older blog posts on http://www.mozillascience.org/blog/ since the site update.

**Comment by acabunoc** [comment]
We don't have one! This is a janky wordpress workaround before we switch to new blog.

**Comment by radaniba** [comment]
I tried to play a bit with the API and figured out that what is in there (rendered in the view) is all you got from the API call 

![screen shot 2015-07-02 at 12 53 15 pm](https://cloud.githubusercontent.com/assets/1666443/8486478/8dcf8804-20b9-11e5-9206-1c68a5cb845a.png)

*see the right side, this is the last json record returned by the api call*

I am wondering : could this be an issue related to the wp config itself ?

**Comment by belkinsa** [comment]
What is the status?

**Comment by acabunoc** [comment]
@belkinsa Very much in the list of features to implement! Would love some help if you have time.

**Comment by belkinsa** [comment]
Ah, I see.  I have the time but not the coding skill, unless it's a simple one that I can learn how to do.

**Comment by acabunoc** [comment]
From @kaythaney:

>any way to prioritize adding a way to see earlier pages of blogposts (and possible a right hand nav)? it's been cited a number of times as a reason people *dont* interact with the blog / lose posts.

>thanks!

>- KT

**Comment by acabunoc** [comment]
Added next & previous buttons to the bottom of the blog page

No easy endpoint for specific months / years, so will be difficult to add that to the sidebar

**Comment by belkinsa** [comment]
\o/, @acabunoc thank you!
