### ISSUE TITLE
Link and title fields swap on every save for the 'More Info' section of Collaborate projects

### ISSUE THREAD

**Issue by jodeleeuw** [mozillascience/site#21]
Under the more info section of the Collaborate project, there are two fields to add a display title and link. Every time I save the page, the values of these fields swap places. This shows up in the live version of the page (the link URL is displayed, with the value of the link being the "title" field), so it's not just a display bug on the form. Saving the page again will cause the fields to swap once more, so edits are possible but require saving the page twice.

**Comment by acabunoc** [comment]
Thanks for this @jodeleeuw! Pushing a fix soon
