### ISSUE TITLE
Email post to discourse

### ISSUE THREAD

**Issue by BillMills** [mozillascience/site#25]
requested by users in [this thread](http://forum.mozillascience.org/t/enable-mailing-list-capabilities-of-discourse/209) - @acabunoc, feasible?

**Comment by acabunoc** [comment]
https://meta.discourse.org/t/new-reply-via-email-support/7764

**Comment by acabunoc** [comment]
https://meta.discourse.org/t/set-up-reply-via-email-support/14003

We'll need a new email account to set this up. I'll check with @jdotpz on how to do this when I talk to him about data privacy later.

**Comment by acabunoc** [comment]
Requested email address for this:

https://github.com/MozillaFoundation/mofo-devops/issues/29

**Comment by acabunoc** [comment]
Left a comment for testing! @BillMills see if reply by email works. Or tag me in a comment and I'll see if it works.

**Comment by acabunoc** [comment]
working! closing
