### ISSUE TITLE
Collaborate Submission Guidelines

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/site#28]
Make a guidelines page to link to before users can submit a project

**Comment by acabunoc** [comment]
Draft is up on staging:
http://staging-mozscilab.herokuapp.com/projects/submit

@kaythaney @BillMills @arlissc

It's longer than I'd like, but I think it has all the relevant points we wanted.

There's a few comments @BillMills brought up that aren't included here (mostly tips on how to engage contributors). I think they might flow better on the submission form itself. Or perhaps in an email to the user once they've submitted a project.

Let me know if this is good to go on production.

**Comment by BillMills** [comment]
@acabunoc this is fantastic, thanks! We will need some comments on how to appeal to and retain contributors, but I agree this makes sense as is; this gets people through the pre-Collaborate steps, and then what to do to actually be successful on the project can come downstream. Thanks!

**Comment by kaythaney** [comment]
+1. I like how crisp and clean this is. Two things that may be worth adding: (1) a note about successful projects having dedicated project leads - make sure the project doesn't get dusty, and there's someone to help answer questions; (2) Something that directly calls out the fact that they need to tease out tasks or problems that others can get started on. This is a tricky one - and we're happy to help, but may be worth calling out specifically.

**Comment by acabunoc** [comment]
Made a few copy changes to highlight teasing out issues / dedicated leads. Can still make changes!

On production now:
http://www.mozillascience.org/projects/submit
