### ISSUE TITLE
Collaborate projects w/ no status

### ISSUE THREAD

**Issue by BillMills** [mozillascience/site#30]
New collaborate projects (and some recently edited ones) have no status assigned.

**Comment by BillMills** [comment]
... including Contributorship Badges - @acabunoc is badges supposed to be delisted?

**Comment by acabunoc** [comment]
Weird. Sounds like the same thing you emailed abt the other day.

**Comment by BillMills** [comment]
oh yeahhhh we did have an email thread about this, it is the same thing :) - welp, now it has an issue. I'll set Badges back to active.

**Comment by acabunoc** [comment]
thanks :)

**Comment by acabunoc** [comment]
I think I pushed a fix -- let me know if this comes up again!
