### ISSUE TITLE
submitting project/editing project leads to blank page

### ISSUE THREAD

**Issue by gedankenstuecke** [mozillascience/site#35]
hey there,
after submitting/editing a new project the site for adding all the information just blanks out, e.g. https://www.mozillascience.org/projects/gedankenstuecke-snpr/edit

Which seems to be a session issue, see this thread on Twitter where we started discussing the thing: https://twitter.com/abbycabs/status/601075816525598720 :smile:

Cheers,
Bastian

**Comment by acabunoc** [comment]
Thanks friend, I'll have time to look at this later today / tomorrow. 

Try again sporadically, the blank page is *probably* a 403 (it was for me). Our CDN has been ignoring cookies and returning cached versions of pages despite being logged in.

**Comment by gedankenstuecke** [comment]
Thanks for looking into it, I will try it again from time to time. :-)

**Comment by acabunoc** [comment]
It randomly started working for me, if that helps.

But this is still something I'll be looking into.

**Comment by gedankenstuecke** [comment]
Still didn't help for me, but I'll keep trying. :8ball:

**Comment by acabunoc** [comment]
Thanks for all your help here @gedankenstuecke.


These steps work for me:

1. Open new session (private tab/clear cache)
2. Log in to mozillascience.org -- do not visit any other pages yet!
3. *then* go to https://www.mozillascience.org/projects/gedankenstuecke-snpr/edit

I think returning a blank response with a 403 status gives us 'Error from Cloudfront' if this page was accessed before login. Maybe I should just return a normal page that says 'access forbidden' in these cases. 

![image](https://cloud.githubusercontent.com/assets/617994/7736122/caad1212-ff0f-11e4-9cc4-416edf7f103e.png)

**Comment by gedankenstuecke** [comment]
Thanks for all your help @acabunoc! This also did the trick for me, I could enter all data and now the submission is under review! :+1:

**Comment by acabunoc** [comment]
Woo! I'll make a new issue for the 403/cloudfront problem :)

**Comment by gedankenstuecke** [comment]
Perfect! :-)
