### ISSUE TITLE
Mixed content warnings

### ISSUE THREAD

**Issue by simonwex** [mozillascience/site#37]
https://forum.mozillascience.org/ is loading over SSL, but includes a bunch of assets that aren't.

You can use the relative protocol if you must because of configuration setup, otherwise just load the assets over SSL.

![image](https://cloud.githubusercontent.com/assets/25260/7966005/33260ef4-09ef-11e5-832c-672201f32cd7.png)

**Comment by acabunoc** [comment]
Thanks @simonwex!

Also on the blog: https://www.mozillascience.org/blog

**Comment by acabunoc** [comment]
Finally fixed on on forum on blog! Thanks to the ssl on our wp instance
