### ISSUE TITLE
Should use CC logo, not the "closed captioning" cc icon in license mark on site.

### ISSUE THREAD

**Issue by billymeinke** [mozillascience/site#38]
Recommend using a CC license badge, or the plain CC logo in the footer instead of the closed captioning icon. The current icon appears to be the latter!

https://en.wikipedia.org/wiki/Closed_captioning

Use one from here instead:

https://creativecommons.org/about/downloads

**Comment by acabunoc** [comment]
thanks for catching that @billymeinke!
