### ISSUE TITLE
FELLOW FOR SCIENCE button mobile reponsive issue

### ISSUE THREAD

**Issue by mmhyamin** [mozillascience/site#44]
**BECOME A MOZILLA FELLOW FOR SCIENCE** button is getting out of the mobile screen which makes the whole site not responsive. It will be okay if we remove ```.pure-button {white-space: nowrap;}``` from  pure-min.css line 11.

![screenshot_2015-08-01-03-11-50](https://cloud.githubusercontent.com/assets/5278142/9150843/857429ea-3e0e-11e5-9e17-4be163f39431.png)
![screenshot_2015-08-01-03-11-59](https://cloud.githubusercontent.com/assets/5278142/9150842/85743958-3e0e-11e5-844f-09c781225de7.png)
![screenshot_2015-08-08-20-23-49](https://cloud.githubusercontent.com/assets/5278142/9150841/8572d72a-3e0e-11e5-8012-78730c7dab4e.png)

**Comment by acabunoc** [comment]
Thanks @mmhyamin!
