### ISSUE TITLE
About Page Suggestion

### ISSUE THREAD

**Issue by belkinsa** [mozillascience/site#47]
https://www.mozillascience.org/about

I have a suggestion for the "About" page, would be worth it to have a separate section for the MSL staff members at Mozilla instead of having it mixed with the community members.

**Comment by mmhyamin** [comment]
@acabunoc could you provide me any "*MSL staff members*" list?

**Comment by acabunoc** [comment]
thanks both! @belkinsa @mmhyamin 

Yes, we'd love to see this change. if anyone is up for making this happen, here is the current staff list:

@kaythaney 
@arlissc 
@zee-moz 
@stephwright 
@acabunoc

**Comment by belkinsa** [comment]
@acabunoc Do you know how hard that is to code?

**Comment by acabunoc** [comment]
Here's the current About page template:
https://github.com/mozillascience/site/blob/master/views/about.jade

**Comment by belkinsa** [comment]
I have the jade page fixed but I don't have the code for the #mslstaff that I referenced in the code.

**Comment by Blahah** [comment]
Any reason this hasn't been merged @acabunoc?

**Comment by acabunoc** [comment]
It doesn't list the staff yet. @mmhyamin - how's that going? let me know if you want to hop on skype to chat about it

**Comment by Blahah** [comment]
That's an excellent reason! Sorry I didn't read the code carefully before asking :). Happy to help move this along @belkinsa if there's anything you'd like to assign to me.

**Comment by mmhyamin** [comment]
@acabunoc My semester final exam is going on that's why I could not pay attention to this issue. I can add this statically for the time being, it will take 15 minutes or so. Once my finals are over, I will make it dynamic.

**Comment by acabunoc** [comment]
No rush! Thanks @mmhyamin -- good luck with your finals :)

**Comment by mmhyamin** [comment]
@acabunoc No problem I almost finished the coding. It will take 5-7 more minutes. I will push the code once I come back from my dinner. I will work again in it as soon as I finish my finals.

**Comment by acabunoc** [comment]
Also, new staff!

@auremoser 

Updated current staff list:
@kaythaney
@arlissc
@zee-moz
@stephwright
@acabunoc
@auremoser

**Comment by auremoser** [comment]
Thank you, @acabunoc!

2015-12-14 15:24 GMT-05:00 Abigail Cabunoc Mayes <notifications@github.com>:

> Also, new staff!
>
> @auremoser <https://github.com/auremoser>
>
> Updated current staff list:
> @kaythaney <https://github.com/kaythaney>
> @arlissc <https://github.com/arlissc>
> @zee-moz <https://github.com/zee-moz>
> @stephwright <https://github.com/stephwright>
> @acabunoc <https://github.com/acabunoc>
> @auremoser <https://github.com/auremoser>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/issues/47#issuecomment-164548859>.
>



-- 
A̴͉̼u͚̮̟̮̩̗̮r̡e̦͖ĺi̻͕̫̠̺a̭̲͖͎ | aureliamoser.com

**Comment by mmhyamin** [comment]
@acabunoc please check. I created a pull request. It's dynamic now. It would have been more easier, if there's a user type for staffs.

**N.B** Sorry I did not pushed the code yesterday. Static code was pretty messed up.

**Comment by auremoser** [comment]
Thank you!
