### ISSUE TITLE
Missing Link On "Training" Page

### ISSUE THREAD

**Issue by belkinsa** [mozillascience/site#52]
https://www.mozillascience.org/training

"CONTACT US

Are you running a program to teach software and open science skills to researchers? Is there a set of lessons or discussions that you would like to see built? Let us know in the Mozilla Science Forum, or join the conversation on twitter @MozillaScience."

The Twitter link is missing the link to the page.

**Comment by acabunoc** [comment]
Thanks @belkinsa!

**Comment by amjadm61** [comment]
It looks like the issue is resolved :-)
So, It would be great if you can close this issue..
