### ISSUE TITLE
Add fellows blogs to website

### ISSUE THREAD

**Issue by acabunoc** [mozillascience/site#62]
**For an MVP** the best spot is probably the 2015 fellows page:
* https://mozillascience.org/fellows/2015
* template: https://github.com/mozillascience/site/blob/master/views/fellows/2015.jade

**Extra**: We could also explore adding this to their user profiles
* [jason](https://mozillascience.org/u/jasonbobe), [joey](https://mozillascience.org/u/joeyklee), [christie](https://mozillascience.org/u/cbahlai), [richard](https://mozillascience.org/u/blahah)
* template: https://github.com/mozillascience/site/blob/master/views/user/user.jade
* Maybe by adding blog to the user in the db:
  * model: https://github.com/mozillascience/site/blob/master/models.js#L92

MVP:
- [x] add to fellows page `/fellows/2015` -- @auremoser 

Extra:
- [x] add to user profiles (`/u/github_id`)

---

owner: @acabunoc
development: @auremoser & @acabunoc

Assigning MVP work to @auremoser, pending time commitment!

**Comment by acabunoc** [comment]
Also, open to suggestions if people know a better spot to add the fellows blogs!
@mozillascience/msl-staff

**Comment by stephwright** [comment]
I like both adding to Fellows page and adding to their user profiles!

**Comment by auremoser** [comment]
Thank you for making this! Very helpful with the files linked. I sketched out the first and am on to the second! Youpee!

**Comment by acabunoc** [comment]
related question- I've been calling this group the "2015 Mozilla Fellows for Science", but maybe they should be the 2016 fellows? or 2015-2016?

**Comment by auremoser** [comment]
That's a good one, I like your original, If they're "born" in 2015, I think they should have that label. :) imho, we had that as Open News Fellows.

**Comment by acabunoc** [comment]
Good to know news does that, too! I'll keep 2015 then :)

**Comment by acabunoc** [comment]
closing!
