### ISSUE TITLE
Finalize moodboard

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#80]
Fantastic v1 is here: https://www.pinterest.com/aure_moser/website/

Next step is to iterate and make it align with Mofo branding/design audit work that's been happening.

Some considerations:
 * consider a broad audience, beyond just hard sciences
 * current logo is well-liked, so design work moving forward can reflect the flat, colorful, multi-toned, "petri dish-like" aesthetic

To finalize, @kristinashu should:
- [ ] Create a moodboard in slides or illustrator exploring specific colours, styling, images, mood and tone. 
- [ ] Create two different directions which the science team can then choose from.

**Comment by hannahkane** [comment]
cc @kristinashu - I don't have assigning privs in this repo, so just tagging you here

**Comment by cassiemc** [comment]
FYI I reached out to Chris Appleton re. the thinking behind the logo. Will post here if he gets back to me.

**Comment by cassiemc** [comment]
From Chris:
It's been a while since I've had a look at the logo, but I've tried to round up some of my early thoughts / keywords I had in mind when designing it initially.

Hope these are helpful! And if not, happy to go into more depth on any of them :)

science 
energy
sparks
catalyst
reactions
fluidity
solution
organic
geometry
transparency
gels / ink droplets
symmetry
brains
rationality
logic
dynamism
chaos
movement
community
sharing info
conversation
dialogue

**Comment by kristinashu** [comment]
I'm pinning a bunch of things here: https://www.pinterest.com/kristinashu/science/
It still doesn't align with our brand, this is just inspiration and then we can align with our brand at the design stage. If anyone wants to be invited to pin on this board, let me know!

**Comment by kristinashu** [comment]
Next step for me will be to create a moodboard in slides or illustrator exploring specific colours, styling, images, mood and tone. If possible I'd like to create two different directions which the science team can then choose from. 

I'm flagging that this will be blocked by the mofo colour ticket https://github.com/MozillaFoundation/Design/issues/139 - I can still move forward but colours will most likely need to be updated once the mofo palette is finalized.

**Comment by hannahkane** [comment]
cool. @kristinashu - should we roll into the next heartbeat?

**Comment by kristinashu** [comment]
@hannahkane yes please

**Comment by cassiemc** [comment]
I updated the first comment with a list of to-do's to finish this off. Those pieces will need design review.

**Comment by kristinashu** [comment]
Here are some slides exploring style for the site https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLUlVjQkJpcWFDSjA/view?usp=sharing
@cassiemc maybe we can discuss? I'm having trouble exploring two different directions while staying on brand.
