### ISSUE TITLE
Finalize content for About page

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#82]
I suggest we start the UI/UX site refresh with a single page, such as About, since we're likely to have that page regardless of what information architecture we land on.

@zee-moz @auremoser @acabunoc - can you come up with content for this page (could be exactly what we have on the /about page now, but I figure there might be changes you want to make)? As we talked about during the kick-off, this can be a collaborative process with design, so the content can evolve as we play around with design ideas.

**Comment by hannahkane** [comment]
See #83 for complementary design ticket

**Comment by auremoser** [comment]
You bet, etherpad here with original content for the tweaking: https://public.etherpad-mozilla.org/p/msl-about 
Edit away!

**Comment by Blahah** [comment]
Unsolicited input:

I'd like to see the about page help people get to know the team better. It used to not even list the team members, so it's better than it was. But still, MSL are building a community, and those interested in joining are going to want to know who shapes and leads that community.

**Comment by auremoser** [comment]
Good point @Blahah :). We have [a wiki](https://wiki.mozilla.org/ScienceLab) with more biographical info on the team, but that content hasn't migrated to the site, maybe it should! I put it in the etherpad.

**Comment by hannahkane** [comment]
Taking this out of current milestone, in order to focus on homepage instead.

**Comment by hannahkane** [comment]
Closing per IA decisions
