### ISSUE TITLE
Create IA proposals

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#84]
We'll propose a couple options for IA for the site refresh, and then share them with community members for feedback (see #81)

**Comment by hannahkane** [comment]
cc @my-le @kristinashu

**Comment by kristinashu** [comment]
Work in progress is happening here: https://docs.google.com/a/mozilla.com/presentation/d/1zZ0sC4_7DOaTFJ5wci986tbPCAgC-yOcV20UTtWNC8E/edit?usp=sharing

**Comment by hannahkane** [comment]
Copying the IA parts of @auremoser's comment on #86, since they're relevant to this ticket, too:

![screen shot 2016-02-18 at 3 56 15 pm](https://cloud.githubusercontent.com/assets/1559703/13157845/1a14d018-d658-11e5-9e52-396bfbaf287a.png)

I also like the 2-part nav, where the header has two calls to action ("Help us grow and improve" button leads to -> http://www.measurementlab.net/contribute), maybe we could put in the [Training](https://mozillascience.org/training) page  "be a mentor" and "be a learner" content at the end of these links. And then the secondary nav has other options.

![screen shot 2016-02-18 at 3 56 23 pm](https://cloud.githubusercontent.com/assets/1559703/13157809/e892c6c6-d657-11e5-8316-fa28a3a866e9.png)

I like Contribute | Collaborate | Convene options for the header more now, like the [CCC option in the nav suggestions](https://docs.google.com/spreadsheets/d/1iiUwf_GTXMdV3vB7Tl0h-bCpm1QBumPExkkTL_ktgMQ/edit#gid=719229321) where:
* **Contribute** leads to "contribution" or ["training"](https://mozillascience.org/training) options (study group, curriculum, calls to join)
* **Collaborate** leads to ["collaborate" platform page](https://mozillascience.org/collaborate)
* **Convene** leads to events, currently on the ["community" page](https://mozillascience.org/community)

#### Sites I like:
1. http://www.measurementlab.net/ - dissected above, not advocating for the carousel at the top however, I find those distracting.
![screen shot 2016-02-18 at 4 33 24 pm](https://cloud.githubusercontent.com/assets/1559703/13158892/0c3eed0c-d65d-11e5-9324-3cd4ed77b8ed.png)

2. https://cartodb.com/ - mostly for the "call to action" built in to highlight blog posts at the top of the page, the "main nav" is always the most recent blog post, because the blog is hidden in sub-navs. I think that gives the site a fresh and active feel for people who only make it to the home page
![screen shot 2016-02-18 at 3 57 29 pm](https://cloud.githubusercontent.com/assets/1559703/13157833/0a98750e-d658-11e5-82c2-1485747e5177.png)
3. https://opennews.org/ - there's a neatness to the ON site too, simple nav with human-readable headers. "who we are" "what we do" "[how to] get involved".
![screen shot 2016-02-18 at 3 59 09 pm](https://cloud.githubusercontent.com/assets/1559703/13157921/65ec15b4-d658-11e5-9e61-eb39a5eb850f.png)
4. http://robdunnlab.com/ - nice alliterative nav - "People" "Projects" "Publications" "Press", I also like how instead of a mission statement there are keywords under the website title.
![screen shot 2016-02-18 at 4 23 59 pm](https://cloud.githubusercontent.com/assets/1559703/13158754/61cde9d6-d65c-11e5-863e-3502e0f3d287.png)
5. https://www.zooniverse.org/ - love how this has a nav and only one thing above the fold, a call to action button. On scroll down, you get a few animated illustrations demo'ing site contents, I like that too.
![screen shot 2016-02-18 at 4 25 37 pm](https://cloud.githubusercontent.com/assets/1559703/13158746/5500820e-d65c-11e5-8ce9-ab3832309b49.png)
6. http://www.milkywayproject.org/ - a zooniverse project, simple site with some stats above the fold, and I like that, the first thing people see is a really simple set of numbers about us, our contributors, our project count, our events/calls count, and a simple "start classifying button" as a single call to action, not a few buttons splintering visitor interest.
![screen shot 2016-02-18 at 4 26 12 pm](https://cloud.githubusercontent.com/assets/1559703/13158749/5a7847da-d65c-11e5-92da-b26dff9b1b4f.png)
7. http://sciencehackny.com/ - not to push to heavy on the retrofuturism but I also like the simplicity of this site (for an event, but still).
![screen shot 2016-02-18 at 4 31 43 pm](https://cloud.githubusercontent.com/assets/1559703/13158865/f2e90a36-d65c-11e5-930d-669f249ee99f.png)

**Comment by hannahkane** [comment]
Also copying @zee-moz's comment from #86, because it's also relevant here!

Looking at the mission, maybe a verb that could come into the IA would be "lead" --- that gives us a way to highlight fellows and the cohort, as well as SG leads? I think the teach/learn separation doesn't work well, as the SGs are very casual and a mix of teaching and learning for all... Slicing and dicing content here gets tricky, since SGs are communities where people learn, and Collaborate is a space for project-based learning but is also a community. etc... hm.

**Comment by hannahkane** [comment]
also copying a relevant piece of @stephwright's comment from #87:

1) I'd like us to be thoughtful about how the home page appears to someone who doesn't know what MoFo and Sci Lab are about. That's why I like the verb tabs because it tells folks what they can do. As much as I love alliteration, not a fan of the three Cs because the words don't seem like they are selected for ease of understanding of a newbie (aren't you contributing if you're collaborating? and what exactly does convening mean to a newbie?).

**Comment by my-le** [comment]
Vanilla + CCC + Verbs + option IV IA have been filled with content items from slide 2, to compare them more easily.
https://docs.google.com/presentation/d/1zZ0sC4_7DOaTFJ5wci986tbPCAgC-yOcV20UTtWNC8E/edit#slide=id.g10156c9576_0_121

**Comment by kristinashu** [comment]
Excellent, thank you @my-le! We can go over these with everyone at our stand up tomorrow.

**Comment by hannahkane** [comment]
Closing this, since we generated new IA proposals. Will open a new ticket to finalize once we incorporate user research results.
