### ISSUE TITLE
Can I have admin privileges for this repo?

### ISSUE THREAD

**Issue by cassiemc** [mozillascience/site#85]
Would like to be able to add labels / assignees / milestones. I suspect @hannahkane needs the same.

@acabunoc can you help?

**Comment by acabunoc** [comment]
done! thanks for the reminder :)

**Comment by hannahkane** [comment]
I can't assign tickets to @my-le or @kristinashu. Is this because they're not members of this repo?

**Comment by acabunoc** [comment]
I *just* added them -- they may need to accept first. Let me know if that works!

**Comment by kristinashu** [comment]
Thanks @acabunoc! I've accepted and was able to assign a ticket to myself.

**Comment by my-le** [comment]
Thanks for adding!

2016-02-17 19:28 GMT+01:00 Kristina <notifications@github.com>:

**Comment by acabunoc** [comment]
hooray! \o/

**Comment by hannahkane** [comment]
Thanks, @acabunoc!
