### ISSUE TITLE
Gather all images

### ISSUE THREAD

**Issue by kristinashu** [mozillascience/site#88]
Do we have an image bank for science? It would be great to start gathering all the images we might want to use on the site. For example, photos from past events, staff profiles, group photo of staff, fellow profiles, group photo of fellows...

We might be able to use some from MozFest: https://www.flickr.com/photos/mozfest/albums/with/72157660181490099

Please add any links to images you can think of or we could start a folder (if you don't have one already). Thanks!

cc @acabunoc @auremoser @zee-moz

**Comment by acabunoc** [comment]
We started a flickr account right before our Working Open Workshop:
https://www.flickr.com/photos/139954518@N06/

But yes, there are a bunch from MozFest. I think @kaythaney and I have a few more floating around we can add to the flickr account

**Comment by kristinashu** [comment]
Thanks @acabunoc! Do you also have the original fellowship profile images? Just in case we want to crop them differently or give them some sort of image treatment.

**Comment by acabunoc** [comment]
As received from them:

![bobe_headshot_12_241_final](https://cloud.githubusercontent.com/assets/617994/13232231/50119e04-d97c-11e5-95d2-55e57c80f8ed.jpg)
![richard_smith_unna](https://cloud.githubusercontent.com/assets/617994/13232232/51ff72d6-d97c-11e5-8dc7-47013c724bfe.jpg)
![jlee crop](https://cloud.githubusercontent.com/assets/617994/13232236/5427e03e-d97c-11e5-8a3d-a1a37c792ad8.jpg)
![headshot 2015](https://cloud.githubusercontent.com/assets/617994/13232238/562cbaee-d97c-11e5-8b27-ffa30c6b8eff.jpg)

**Comment by stephwright** [comment]
Should I add photos from tweets and other events like Summit and Fellows
onboarding & Mozlando?

On Mon, Feb 22, 2016 at 12:53 PM, Abigail Cabunoc Mayes <
notifications@github.com> wrote:

> As received from them:
>
> [image: bobe_headshot_12_241_final]
> <https://cloud.githubusercontent.com/assets/617994/13232231/50119e04-d97c-11e5-95d2-55e57c80f8ed.jpg>
> [image: richard_smith_unna]
> <https://cloud.githubusercontent.com/assets/617994/13232232/51ff72d6-d97c-11e5-8dc7-47013c724bfe.jpg>
> [image: jlee crop]
> <https://cloud.githubusercontent.com/assets/617994/13232236/5427e03e-d97c-11e5-8a3d-a1a37c792ad8.jpg>
> [image: headshot 2015]
> <https://cloud.githubusercontent.com/assets/617994/13232238/562cbaee-d97c-11e5-8b27-ffa30c6b8eff.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/issues/88#issuecomment-187378239>.
>



-- 
Stephanie Wright
--------------------------------------------------------------------------------------
Open Data Training Lead, Mozilla Science Lab
Twitter @shefw  | GitHub @stephwright | Skype: stephanie_4504
ORCID: 0000-0003-3829-318X
"The opposite of 'open' isn't 'closed'.  The opposite of 'open' is
'broken'." ~ John Wilbanks

**Comment by kristinashu** [comment]
Yes, please add those event photos. Tweets might be too low resolution to use but if you have the original photos that would be great.

**Comment by acabunoc** [comment]
Also tagging @joeyklee who took some awesome photos at mozfest & WOW. Did you end up sharing them on flickr?

**Comment by joeyklee** [comment]
Hi! I've got a few photos from Onboarding, Moz fest, and the WOW workshop. I haven't added them to the flickr - are there login details lying around to post to or should I share via dropbox?

**Comment by kristinashu** [comment]
Thanks @joeyklee! I'm not sure what the login info is for flickr but I think dropbox might be easiest anyways.

**Comment by acabunoc** [comment]
I put them all up on the mozillascience flickr!
https://www.flickr.com/photos/139954518@N06/

**Comment by kristinashu** [comment]
Ok excellent, thanks! Do you think that's it for photos, can we close this ticket?

**Comment by joeyklee** [comment]
Those are all of the photos I have for now.

**Comment by acabunoc** [comment]
Closing the ticket :)
