### ISSUE TITLE
Gather all logos

### ISSUE THREAD

**Issue by kristinashu** [mozillascience/site#89]
Please add any relevant logos. I've started a folder with the Science Lab logo but if you could please add any other ones we might need (partners, supporters, hosts...). 

Vector files (.ai, .eps or .svg) would be ideal. 

Please add to this ticket or to this folder: https://drive.google.com/a/mozilla.com/folderview?id=0B2irLVDJivhLVjM5SVlvc3otam8&usp=sharing

cc @acabunoc @auremoser @zee-moz

**Comment by acabunoc** [comment]
I just shared this folder with you: https://drive.google.com/drive/folders/0Bz4NUCbMj6c9U29jeTdUS2l0cGc

That should have most logos you need! Let me know if this other folder is okay

**Comment by kristinashu** [comment]
Great, thanks @acabunoc!
