### ISSUE TITLE
Draft Analytics report

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#90]
I know that the current site analytics may not be entirely reflective of our goals, but let's summarize what we can learn from the current site's analytics. I think it will inform our decisions moving forward.

@kristinashu - do you want to lead on this? You did a great job with this for the Teach site.

@acabunoc - are you able to grant Analytics access for @kristinashu and me?

**Comment by acabunoc** [comment]
I think we'll need to talk to @adamlofting

![screen shot 2016-02-24 at 08 46 18](https://cloud.githubusercontent.com/assets/617994/13287082/1907fb94-dad3-11e5-906f-390af13dcc1f.png)

**Comment by adamlofting** [comment]
I'm not an admin on this profile either, I'll file a ticket now to request access. It's usually pretty quick.

**Comment by adamlofting** [comment]
Ticket is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1250886

**Comment by hannahkane** [comment]
thanks, @adamlofting !

**Comment by kristinashu** [comment]
Thanks @adamlofting! 

@hannahkane Yes, I'm happy to do this once we get access.

**Comment by hannahkane** [comment]
Unblocked! We should now have access.

**Comment by kristinashu** [comment]
Here's an overview of the analytics https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLR2ZBSEcxTTM1VVU/view?usp=sharing

cc @hannahkane @kaythaney @acabunoc @auremoser @stephwright @zee-moz @cassiemc
