### ISSUE TITLE
Run phase 1 of user research

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#91]
The [user research plan](https://docs.google.com/document/d/1oe8AwqMiKh97558mC5Q9Scs3RWrnFPsCrDxrlX5HCw4/edit#heading=h.4r3jdiuhxn9l) details a phase 1 that asks community members to participate in an asynchronous, virtual card sorting activity. Results will be used to inform IA including nav structure and terminology.

Email sent:
- [x] Bastian
- [x] Fatma 
- [x] Amel
- [x] Joey
- [x] Rob
- [x] Richard
- [ ] Jason
- [x] Christie
- [x] Hana
- [x] Amira
- [x] Ancon

Finished:
- [x] Bastian
- [ ] Fatma 
- [ ] Amel
- [x] Joey
- [x] Rob
- [x] Richard
- [ ] Jason
- [x] Christie
- [x] Hana
- [x] Amira
- [x] Ancon

**Comment by kristinashu** [comment]
I sent the email to Sabrina to test the instructions. It made sense and her and she even sent me back a proposed IA! 

Aurelia is sending out an intro email to all the possible participants and then I'll send Phase 1 (Generative testing) to the first 4 participants. Depending how Phase 1 goes, we will either send out Phase 1 or 2 to the rest of the participants.

Excited to see what they come up with!

**Comment by kristinashu** [comment]
Everyone has been very keen to help out! I've sent emails to 6 participants and will hold off until we get some results before sending the rest (just to make sure everything is clear and to asses if we want to continue with Phase 1 or jump to Phase 2).

**Comment by kristinashu** [comment]
cc @auremoser just to keep you in the loop since I haven't been cc'ing you in the reply emails.

**Comment by auremoser** [comment]
Oh thanks! @kristinashu

**Comment by kristinashu** [comment]
Most of the results are in! All the responses are here https://docs.google.com/a/mozilla.com/document/d/1oveyDCRLWtyXBSkLyrJGtMzRkAw6req2n5ARSO5d-gI/edit?usp=sharing and in a chart here https://docs.google.com/a/mozilla.com/spreadsheets/d/1lAqFGWEOrqA1VJwc8ihNmzV-iEINeM9Oe-NuVkXvub0/edit?usp=sharing

Today I will be summarizing these findings.

**Comment by kristinashu** [comment]
Here's a summary of the findings along with a few questions, would love to hear your thoughts @kaythaney @acabunoc @auremoser @stephwright @zee-moz @cassiemc 
https://docs.google.com/a/mozilla.com/document/d/1oveyDCRLWtyXBSkLyrJGtMzRkAw6req2n5ARSO5d-gI/edit?usp=sharing
Thanks!

**Comment by kaythaney** [comment]
thanks! comments added.

On Thu, Mar 3, 2016 at 3:00 PM, Kristina <notifications@github.com> wrote:

> Here's a summary of the findings along with a few questions, would love to
> hear your thoughts @kaythaney <https://github.com/kaythaney> @acabunoc
> <https://github.com/acabunoc> @auremoser <https://github.com/auremoser>
> @stephwright <https://github.com/stephwright> @zee-moz
> <https://github.com/zee-moz> @cassiemc <https://github.com/cassiemc>
>
> https://docs.google.com/a/mozilla.com/document/d/1oveyDCRLWtyXBSkLyrJGtMzRkAw6req2n5ARSO5d-gI/edit?usp=sharing
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozillascience/site/issues/91#issuecomment-191938305>.
>



-- 
@kaythaney <http://twitter.com/kaythaney/>
@MozillaScience <http://twitter.com/mozillascience>

**Comment by hannahkane** [comment]
I think we can close this ticket, since Phase 1 has been completed. Learnings will inform final decisions on IA and copywriting.

If we want to solicit more input from users (as described in the original plan), we can open a new ticket.
