### ISSUE TITLE
Finalize IA

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#92]
Inform our decision with:
- [user research feedback](https://github.com/mozillascience/site/issues/91)
- [summary of current site analytics](https://github.com/mozillascience/site/issues/90)

Consider doing an evaluative user test (might require wireframes for several pages) to validate

**Comment by cassiemc** [comment]
@hannahkane @kristinashu @my-le Can you link or post the IA versions we are testing please?

**Comment by kristinashu** [comment]
@cassiemc there is a ticket with the Phase 1 testing details https://github.com/mozillascience/site/issues/91

**Comment by kristinashu** [comment]
I've updated the IA to better reflect our user research. There are two IA directions. Each version has a short intro with the main level menu items followed by a more details IA.

You can download the PDF https://drive.google.com/a/mozilla.com/file/d/0B2irLVDJivhLTEs2NUFTdDA5ZGs/view?usp=sharing or look on Redpen for easier commenting https://redpen.io/p/je92d9783cd2855569

Although section nomenclature is important and if you have thoughts please share, at this stage the main focus should be on how the different content types are grouped.

cc @hannahkane @kaythaney @acabunoc @auremoser @stephwright @zee-moz @cassiemc @my-le

**Comment by hannahkane** [comment]
Thanks, @kristinashu. Just sent a calendar invite for tomorrow. Hoping we can meet to make a final decision.

**Comment by kristinashu** [comment]
Thanks everyone for the feedback today. Here is the updated version: https://redpen.io/uk017bb24968e69f1b
I've added Resources as a main level menu item and shortened the other headings to "Projects" and "Blog".

**Comment by kristinashu** [comment]
Closing this ticket but please feel free to leave feedback in the redpen
