### ISSUE TITLE
Wireframes for Fellowship page

### ISSUE THREAD

**Issue by kristinashu** [mozillascience/site#93]
In an effort to move forward we will treat Fellowship as a main level navigation item and we can adapt the wireframes later if we decide to make Fellowship a secondary menu item.

For now, we can pull copy from the current site and then see if we're missing any content once we have the rough wireframes.

We will do what we think is best suited for science but for context here are some references:
In an effort to streamline fellowship content across Advocacy, Science and Open News, here is a doc comparing content of the three: https://docs.google.com/a/mozilla.com/spreadsheets/d/1c-JsTdHUSX7Z_cOxlDZ8z3rFgZOLPt9aeYKTpwK1b4c/edit?usp=sharing
We can also reference https://advocacy.mozilla.org/open-web-fellows/ although the exact structure might not necessary apply. 

cc @my-le

**Comment by cassiemc** [comment]
@my-le @kristinashu Can you post here the wireframes you shared in the stand earlier this week?

**Comment by my-le** [comment]
Based on Advocacy Fellows Page.
01) Overview Part:

![msl-fellowship-wireframe-lyt02-p01](https://cloud.githubusercontent.com/assets/10426601/13506854/441b7bb8-e180-11e5-87e4-fff174395f0d.jpg)

**Comment by my-le** [comment]
02) Info Part:

![msl-fellowship-wireframe-lyt02-p02](https://cloud.githubusercontent.com/assets/10426601/13506877/5f4c0998-e180-11e5-8c2e-1c24c52be0a5.jpg)

**Comment by my-le** [comment]
03) Fellows Part Option A

![msl-fellowship-wireframe-lyt02-p03](https://cloud.githubusercontent.com/assets/10426601/13506887/728b6cc4-e180-11e5-9eb8-b562d7c90966.jpg)

**Comment by my-le** [comment]
03) Fellows Part Option B

![msl-fellowship-wireframe-lyt02-p04](https://cloud.githubusercontent.com/assets/10426601/13506899/85007278-e180-11e5-9404-8df98605769c.jpg)

**Comment by cassiemc** [comment]
@my-le Thanks for this! What are the latest redpen links? (If you could list the url's / link directly to each redpen intended for review that would be super helpful!)

**Comment by my-le** [comment]
@cassiemc You're right, sorry :D

**Comment by kristinashu** [comment]
Closing this one since Fellowships with fall under the Programs page https://github.com/mozillascience/site/issues/100

**Comment by hannahkane** [comment]
@kristinashu - fine to close for now, but just want to check my understanding. The individual programs will still have their own pages, right? Accessible via the Programs Landing page and the pulldown menu in the nav?

**Comment by kristinashu** [comment]
Yes that's right. It will be multiple pages but I'd like to look at it as a whole so I think one ticket will be good, even though it will be one meaty ticket.
