### ISSUE TITLE
Wireframes for Blog

### ISSUE THREAD

**Issue by kristinashu** [mozillascience/site#94]
Create wireframes for the blog page. Current site https://www.mozillascience.org/blog

cc @my-le

**Comment by cassiemc** [comment]
Any update @my-le @kristinashu ?

**Comment by my-le** [comment]
1st iteration on Red Pen: https://redpen.io/xd85ac9218cc209f47

![04-msl-blog-wireframe-lyt01-p01](https://cloud.githubusercontent.com/assets/10426601/13533017/c8516c5e-e22e-11e5-981b-ff5571f6f398.jpg)

**Comment by my-le** [comment]
2nd iteration with comments on Red Pen: https://redpen.io/zwe162ac4d04a91697

![04-msl-blog-wireframe-lyt01-p02](https://cloud.githubusercontent.com/assets/10426601/13533124/45119098-e22f-11e5-9ca2-3b30c1c27a49.jpg)

**Comment by kristinashu** [comment]
Closing this ticket in light of the work happening in https://github.com/mozilla/wp-calypso/issues/20
