### ISSUE TITLE
Finalize visual aspects of brand direction

### ISSUE THREAD

**Issue by hannahkane** [mozillascience/site#96]
First step: review the [moodboard](https://github.com/mozillascience/site/issues/80)

**Comment by hannahkane** [comment]
@cassiemc - can you update this ticket with more information about what you expect the outcome of the heartbeat to be?

**Comment by cassiemc** [comment]
Actually @kristinashu outlined this quite well in https://github.com/mozillascience/site/issues/80. I'll close this issue in favour of that one.

> Next step for me will be to create a moodboard in slides or illustrator exploring specific colours, styling, images, mood and tone. If possible I'd like to create two different directions which the science team can then choose from.
