### ISSUE TITLE
Determine URLs

### ISSUE THREAD

**Issue by kristinashu** [mozillascience/site#99]
Based on the IA, I'm proposing the following URLs https://redpen.io/gpdfe4cfad5fac095e

cc @cassiemc @hannahkane

**Comment by hannahkane** [comment]
wfm!

**Comment by kristinashu** [comment]
Here are the proposed URLs https://redpen.io/gpdfe4cfad5fac095e

Some edits might be made if the IA changes but I just want to make sure everyone is good with the overall structure. Mainly, moving to science.mozilla.org

cc @kaythaney @acabunoc @auremoser @stephwright @zee-moz @cassiemc

**Comment by kristinashu** [comment]
We discussed this at our stand this morning and we are good with the general structure of the URLs.
